# Generated by Django 3.1.7 on 2021-03-19 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roadtrip', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SimpleForm',
            new_name='UserLink',
        ),
        migrations.RenameField(
            model_name='userlink',
            old_name='basic_field',
            new_name='first_name',
        ),
    ]
